#!/usr/bin/python

import audio
import subprocess

def main():
    try:
        raw = audio.send_command_to_music_player("Get", print_reply=True,
            cmd_prefix="org.freedesktop.DBus.Properties", msg_payload="string:Metadata " * 2)
    except subprocess.CalledProcessError:
        return
    title = "?"
    album = "?"
    author = "?"
    empty = True
    # Parsing this manually is mildly silly
    key = ""
    for line in raw.split("\n"):
        line = line.strip()
        if "string" in line:
            line = line.replace("variant", "").strip()
            if "xesam:" in line:
                key = line.split(":")[1][:-1]
            else:
                value = line.split('"')[1]
                if key == "album":
                    empty = False
                    album = value
                if key == "title":
                    empty = False
                    title = value
                if key == "artist":
                    empty = False
                    author = value
    if title.endswith(".mp3"):
        title = title[:-4]
    if not empty:
        print(" | ".join([title, album, author]))

if __name__ == "__main__":
    main()
