#!/usr/bin/python

import audio
import os

def main():
    files = [f for f in os.listdir(".") if f.endswith(".mp3")]
    for f in files:
        d = audio.get_file_duration_seconds(f)
        if d < 1.5:
            print("Deleting '" + f + "' which lasts " + str(d) + " seconds")
            os.system("rm " +f)

if __name__ == "__main__":
    main()
