#!/usr/bin/python

import os
import sys
import time

def main(seconds):
    os.system("audiomediaplayertogglemute")
    time.sleep(seconds)
    os.system("audiomediaplayertogglemute")

if __name__ == "__main__":
    main(int(sys.argv[1]))
