#!/usr/bin/python3
"""Raises the system's audio volume."""
import os

HOME = os.path.expanduser("~")

os.system("amixer -D pulse set 'Master' 5%+")
os.system("/usr/bin/play -q " + HOME + "/bus/reference/sounds/water_droplet.mp3")
