#!/usr/bin/python
"""Prints the system's audio volume."""
import re
import shlex
import subprocess

PATTERN = re.compile(r".*\s+/\s+(\d+)%\s+/\s+.*")

def main():
    raw = subprocess.check_output(shlex.split("pactl get-sink-volume @DEFAULT_SINK@")).decode()
    for l in raw.split("\n"):
        matches = PATTERN.match(l)
        if matches:
            print(matches[1])
            # Only print one
            return

if __name__ == "__main__":
    main()
