#!/usr/bin/python

import os

import windowmanager

NOTIF_ID = 78365

def main():
    os.system("playerctl play-pause")
    icon_path = os.path.join(os.path.expanduser("~"), "bus", "reference", "icons", "play_pause.svg")
    windowmanager.notify("", icon_path, NOTIF_ID)

if __name__ == "__main__":
    main()

