#!/usr/bin/python

import audio
import os

def main():
    files = [f for f in os.listdir(".") if f.endswith(".mp3")]
    [longest_duration, file_with_longest_duration] = audio.find_longest_file(files)
    print(f"Longest: {file_with_longest_duration} with {longest_duration} seconds")

if __name__ == "__main__":
    main()
