#!/usr/bin/python
"""Lowers the system's audio volume."""

import os

HOME = os.path.expanduser("~")

os.system("pactl -- set-sink-volume @DEFAULT_SINK@ -5%")
os.system("/usr/bin/play -q " + HOME + "/bus/reference/sounds/water_droplet.mp3")
