#!/usr/bin/python

import os
import shlex
import subprocess
import sys

from virtualdesktops import ARABIC, ROMAN, CHINESE

N_ROWS = 3
N_COLS = 3

ARABIC_NUMERALS = ARABIC.split(" ")
ROMAN_NUMERALS = ROMAN.split(" ")
CHINESE_NUMERALS = CHINESE.split(" ")

ALL_NUMERALS = [
    ARABIC_NUMERALS, ROMAN_NUMERALS, CHINESE_NUMERALS,
]

def switch(current, direction):
    target = current
    if direction == "l":
        is_leftmost = (current % N_COLS == 1)
        if not is_leftmost:
            target = current - 1
    if direction == "r":
        is_rightmost = (current % N_COLS == 0)
        if not is_rightmost:
            target = current + 1
    if direction == "u":
        is_topmost = (current <= N_COLS)
        if not is_topmost:
            target = current - N_COLS
    if direction == "d":
        is_bottommost = (current > (N_ROWS - 1) * N_COLS)
        if not is_bottommost:
            target = current + N_COLS
    if target != current:
        focused_monitor = subprocess.check_output(shlex.split(
            "bspc query -M -d focused --names")).decode().strip()

        monitor_ids = subprocess.check_output(shlex.split(
            "bspc query -M --names")).decode().strip().split("\n")
        i = 0
        for monitor_id in monitor_ids:
            target_numeral = ALL_NUMERALS[i % 3][target - 1]
            os.system("bspc monitor -f " + monitor_id)
            os.system("bspc desktop -f " + str(target_numeral))
            i += 1

        # Restore focused monitor
        os.system("bspc monitor -f " + focused_monitor)
        icon_filename = (
            "workspace_"
            "" + str(N_ROWS) + "x"
            "" + str(N_COLS) + "_"
            "" + str(target) + ""
            ".svg"
        )
        icon_path = os.path.join(os.path.expanduser("~"), "bus", "reference", "workspace_icons",
            icon_filename)
        os.system("notify-send --urgency=low --expire-time=500 ' ' --icon " + icon_path)

if __name__ == "__main__":
    DIRECTION = sys.argv[1]
    CURRENT = subprocess.check_output(
        shlex.split("bspc query -D -d focused --names")).decode().strip()
    if CURRENT in ROMAN_NUMERALS:
        CURRENT = ROMAN_NUMERALS.index(CURRENT) + 1
    if CURRENT in CHINESE_NUMERALS:
        CURRENT = CHINESE_NUMERALS.index(CURRENT) + 1
    switch(int(CURRENT), DIRECTION)
