#!/usr/bin/python3

import os
import shlex
import subprocess
import sys

N_ROWS = 3
N_COLS = 3

ROMAN_NUMERALS = [
  "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX",
]

def switch(current, direction):
    target = current
    if direction == "l":
        is_leftmost = (current % N_COLS == 1)
        if not is_leftmost:
            target = current - 1
    if direction == "r":
        is_rightmost = (current % N_COLS == 0)
        if not is_rightmost:
            target = current + 1
    if direction == "u":
        is_topmost = (current <= N_COLS)
        if not is_topmost:
            target = current - N_COLS
    if direction == "d":
        is_bottommost = (current > (N_ROWS - 1) * N_COLS)
        if not is_bottommost:
            target = current + N_COLS
    if target != current:
        os.system("bspc monitor -f eDP-1; bspc desktop -f " + str(target))
        target_roman = ROMAN_NUMERALS[target - 1]
        os.system("bspc monitor -f DP-1; bspc desktop -f " + str(target_roman))

if __name__ == "__main__":
    DIRECTION = sys.argv[1]
    CURRENT = subprocess.check_output(
        shlex.split("bspc query -D -d focused --names")).decode().strip()
    if CURRENT in ROMAN_NUMERALS:
        CURRENT = ROMAN_NUMERALS.index(CURRENT) + 1
    print(CURRENT)
    switch(int(CURRENT), DIRECTION)
