#!/usr/bin/python

import os

from pathlib import Path

GNOME_PROJECTS = [
    "babl",
    "gegl",
    "gimp",
    "gnome-terminal",
]

HYPR_PROJECTS = [
    "Hyprland",
    "aquamarine",
]

def main():
    dirname = Path.cwd().name
    if dirname in GNOME_PROJECTS:
        os.system("gnbuild")
    elif dirname.startswith("hypr") or dirname in HYPR_PROJECTS:
        os.system("hyprbuild")
    elif dirname == "pwvucontrol":
        os.system("pwvucontrolbuild")
    elif dirname == "RetroArch":
        os.system("./fetch-submodules.sh && ./configure && make -j`nproc`")
    else:
        print("Sorry, I don't know how to build this project")

if __name__ == "__main__":
    main()
