#!/usr/bin/python

import os

from pathlib import Path

GNOME_PROJECTS = [
    "babl",
    "gegl",
    "gimp",
    "gnome-terminal",
]

HYPR_PROJECTS = [
    "Hyprland",
    "aquamarine",
]

def main():
    dirname = Path.cwd().name
    if dirname in GNOME_PROJECTS:
        os.system("gnbuild")
    if dirname.startswith("hypr") or dirname in HYPR_PROJECTS:
        os.system("hyprbuild")

if __name__ == "__main__":
    main()
