#!/usr/bin/python

import os
import sys

import cal

if __name__ == "__main__":
    event = cal.get_next_event()
    if event is not None:
        print(event)
    else:
        print("No next event today")
