#!/usr/bin/python3

import glob
import os
import sys

import util

cbz = sys.argv[1]
base_name = cbz.replace(".cbz", "")
base_name = util.sanitize_for_filename(base_name)
print(base_name + "...")
util.silent("unzip " + cbz + " -d " + base_name)
os.chdir(base_name)
util.run_bin_cmd("sanitizefilenames", args="*")

# print("Ignore any 'no such file' error with */*.jpg or */*.png below...")

jpgs = glob.glob("*/*.jpg")
pngs = glob.glob("*/*.png")

if len(jpgs):
    cmd = "mv -f " + " ".join(['"' + j + '"' for j in jpgs]) + " ."
    os.system(cmd)
if len(pngs):
    cmd = "mv -f " + " ".join(['"' + p + '"' for p in pngs]) + " ."
    os.system(cmd)

util.run_bin_cmd("sanitizefilenames", args="*")
imgs = [f for f in os.listdir(".") if f.endswith(".jpg") or f.endswith(".png")]
util.run_bin_cmd("mkpdffromimgs", args=" ".join(sorted(imgs)))
os.system("mv output.pdf ../" + base_name + ".pdf")
os.chdir("..")
os.system("rm -rf " + base_name)
