#!/usr/bin/python3

import os
import sys
import util

if util.is_linux():
    os.system("cat " + sys.argv[1] + " | xclip -sel clip")
elif util.is_mac():
    os.system("cat " + sys.argv[1] + " | pbcopy")
print("Copied contents to clipboard")
