#!/usr/bin/python

import os
import shlex
import subprocess
import sys
import util

if __name__ == "__main__":
  ARGS = " ".join(sys.argv[1:])

  COMMON_OPTIONS = "-u"
  BIN = "/usr/bin/diff"

  if util.is_mac():
    proc = subprocess.run(shlex.split("grc " + BIN + " " + COMMON_OPTIONS + " " + ARGS))
    sys.exit(proc.returncode)
  else:
    proc = subprocess.run(shlex.split(BIN + " " + COMMON_OPTIONS + " --color=always " + ARGS))
    sys.exit(proc.returncode)

