#!/usr/bin/python3

import os
import subprocess

NUMBER_OF_ENTRIES_TO_SHOW = 20

PATTERNS_TO_IGNORE = [
  "/.git"
]

def size_key(item):
    return item["size"]

def which_to_delete(a, b):
    # if len(second) > len(first):
        # return (second, first)
    # return (first, second)
    if second > first:
        return (second, first)
    return (first, second)

print("Checking...")
output = subprocess.check_output(["fdupes", "-rS", "."]).decode()

groups = output.split("\n\n")
entries = []

for el in groups:
    parts = el.split("\n")
    if len(parts) < 3:
        continue
    if not "bytes each" in parts[0]:
        continue
    new_entry = {
        "size": int(parts[0][: -len(" bytes each:")]),
        "files": [parts[1], parts[2]],
    }
    files = new_entry["files"]
    entries.append(new_entry)

entries.sort(key=size_key, reverse=True)

for e in entries:
    first = e["files"][0]
    second = e["files"][1]
    skip = False
    for i in PATTERNS_TO_IGNORE:
        if i in first and i in second:
            skip = True
            continue
    if skip:
        continue
    (deletion_candidate, other) = which_to_delete(first, second)
    size_str = str(int(e["size"] / 1024 / 1024)) + "M"
    print("\nSame files, size " + size_str + ":")
    print("\t" + ("X" if first == deletion_candidate else " ") + " " + first)
    print("\t" + ("X" if second == deletion_candidate else " ") + " " + second)
    answer = input("--> Delete? [Enter] for Yes, n for No, o for Delete Other: ")
    if answer.strip() == "":
        print("Deleting")
        os.system("rm '" + deletion_candidate + "'")
    elif answer.strip() == "n":
        print("Skipping")
    elif answer.strip() == "o":
        print("Deleting the other file")
        os.system("rm '" + other + "'")
    else:
        print("Not sure what that means. Skipping.")
