#!/usr/bin/python

import os
import time

from datetime import datetime

oldest_file = None
oldest_mtime = time.time()

for path, _, filenames in os.walk(os.getcwd()):
    for f in filenames:
        f_full = os.path.join(path, f)
        if not os.path.exists(
            os.readlink(f_full) if os.path.islink(f_full) else f_full
        ):
            continue
        if os.path.getmtime(f_full) < oldest_mtime:
            oldest_mtime = os.path.getmtime(f_full)
            oldest_file = f_full

print(
    "Oldest file: " + oldest_file + " which was modified last on "
    "" + datetime.utcfromtimestamp(oldest_mtime).strftime("%Y-%m-%d %H:%M:%S") + " UTC"
)
