#!/usr/bin/python3

import os
import time

from datetime import datetime

newest_file = None
newest_mtime = 0

for path, _, filenames in os.walk(os.getcwd()):
  for f in filenames:
    f_full = os.path.join(path, f)
    if not os.path.exists(os.readlink(f_full) if os.path.islink(f_full) else f_full):
      continue
    if os.path.getmtime(f_full) > newest_mtime:
      newest_mtime = os.path.getmtime(f_full)
      newest_file = f_full

print("Newest file: " + newest_file + " which was modified last on "
      "" + datetime.utcfromtimestamp(newest_mtime).strftime(
          '%Y-%m-%d %H:%M:%S') + " UTC")
