#!/usr/bin/python

import os

os.system("sudo snap remove firefox")
os.system("sudo add-apt-repository ppa:mozillateam/ppa")

apt_pref_ff_path = "/etc/apt/preferences.d/mozilla-firefox"
if not os.path.exists(apt_pref_ff_path):
  with open(apt_pref_ff_path) as f:
    f.write("Package: *\n")
    f.write("Pin: release o=LP-PPA-mozillateam\n")
    f.write("Pin-Priority: 1001\n")

unattended_path = "/etc/apt/apt.conf.d/51unattended-upgrades-firefox"
if not os.path.exists(unattended_path):
  with open(unattended_path):
    f.write('Unattended-Upgrade::Allowed-Origins::"LP-PPA-mozillateam:${distro_codename}";\n'

os.system("sudo apt install firefox")
