#!/usr/bin/python3

# For some reason, the git remote for this repository regularly gets changed to
# the http protocol instead of git. Fix this.

import os

import util

cmd = util.is_mac() ? "sed -I" else "sed -i"
os.system(cmd + " 's#https://github.com/#git@github.com:#g' .git/config")
