#!/usr/bin/python

# For some reason, the git remote for this repository regularly gets changed to
# the http protocol instead of git. Fix this.

import os

import util

cmd = "sed -I \"\"" if util.is_mac() else "sed -i"
os.system(cmd + " 's#https://github.com/#git@github.com:#g' .git/config")
