#!/usr/bin/python3

import os
import sys

sys.path.append(os.path.join(os.path.expanduser("~"), "repos", "sak"))
import util

home = os.path.expanduser("~")
gimp_config_dir = os.path.join(
    os.path.expanduser("~"), "bus", "config", "config", "GIMP", "2.10"
)
# gimp_config_dir = os.path.join(os.path.expanduser("~"), "bus", "config",
#    "gimp-2.8")

if len(sys.argv) > 1:
    activity = sys.argv[1]
else:
    # Assume draw
    activity = "draw"

os.chdir(gimp_config_dir)

ram_gb = util.get_ram_gb()

if activity == 'draw':
    tile_cache_size = int(0.7 * ram_gb)
    undo_size = int(0.2 * ram_gb)
else:
    tile_cache_size = int(0.2 * ram_gb)
    undo_size = int(0.1 * ram_gb)


print(
    "Adjusting for RAM = "
    + str(ram_gb)
    + " with cache size "
    + str(tile_cache_size)
    + " and undo size "
    + str(undo_size)
)

is_mac = util.is_mac()
sed = "sed -I" if is_mac else "sed -i"
command = sed + " 's/TILE_CACHE_SIZE/" + str(tile_cache_size) + "G/' gimprc"
os.system(command)
# print(command)
command = sed + " 's/UNDO_SIZE/" + str(undo_size) + "G/' gimprc"
# print(command)
os.system(command)

os.chdir(home)
