#!/usr/bin/python

import os
import sys
import util

USE_EXPERIMENTAL = False

def main(argv):
    arguments = []
    if len(argv) > 1:
        arguments = sys.argv[1:]

    orig_dir = os.getcwd()
    full_arguments = [
        # "--no-splash",
    ]
    for a in arguments:
        full_arguments.append(os.path.join(orig_dir, a))

    util.run_bin_cmd("gimpsetup", args="draw")
    if util.is_mac():
        os.system("open /Applications/GIMP.app")
    else:
        # os.system("/usr/bin/gimp-2.8 " + " ".join(full_arguments))
        cmd = "/usr/bin/gimp-3.0"
        if USE_EXPERIMENTAL:
            cmd = os.path.expanduser("~/jhbuild/install/bin/gimp")
        full_cmd = cmd + " " + " ".join(full_arguments)
        print(full_cmd)
        os.system(full_cmd)
    util.run_bin_cmd("gimpteardown")

if __name__ == "__main__":
    main(sys.argv)
