#!/usr/bin/python

import argparse
import os
import util

PARSER = argparse.ArgumentParser()
PARSER.add_argument("files", nargs="*")
PARSER.add_argument("-d", dest="dev", action="store_true",
                    help=("Use the experimental build from ~/jhbuild instead "
                          "of the installed one."))

def main(args):
    orig_dir = os.getcwd()
    full_arguments = [
        # "--no-splash",
    ]
    for a in args.files:
        full_arguments.append(os.path.join(orig_dir, a))

    util.run_bin_cmd("gimpsetup", args="draw")
    if util.is_mac():
        os.system("open /Applications/GIMP.app")
    else:
        # os.system("/usr/bin/gimp-2.8 " + " ".join(full_arguments))
        cmd = "/usr/bin/gimp-3.2"
        if args.dev:
            cmd = os.path.expanduser("~/jhbuild/install/bin/gimp-3.3")
        full_cmd = cmd + " " + " ".join(full_arguments)
        print(full_cmd)
        os.system(full_cmd)
    util.run_bin_cmd("gimpteardown")

if __name__ == "__main__":
    main(PARSER.parse_args())
