#!/usr/bin/python3

import os
import sys

sys.path.append(os.path.join(os.path.expanduser("~"), "repos", "sak"))
import util

home = os.path.expanduser("~")
gimp_config_dir = os.path.join(
    os.path.expanduser("~"), "bus", "config", "config", "GIMP", "2.10"
)

# gimp_config_dir = os.path.join(os.path.expanduser("~"), "bus", "config",
#    "gimp-2.8")

os.chdir(gimp_config_dir)
os.system("git checkout gimprc")
os.system("git checkout sessionrc menurc colorrc contextrc devicerc")
os.system("git checkout tool-options/\*")
util.run_bin_cmd("regularcleanup")
