#!/usr/bin/python3
"Deletes branches that have no differences with the given branch."

import os
import shlex
import subprocess
import sys
import util

if __name__ == "__main__":
    # What is the reference branch?
    branches = util.get_git_branches()
    if len(sys.argv) == 1:
        for default in ["master", "main"]:
            if default in branches:
                ref_branch = default
                break

    cleaned_up = 0
    for branch in branches:
        if branch == ref_branch:
            continue
        print("Switching to '" + branch + "'...")
        os.system("git checkout '" + branch + "'")
        diffs = (
            subprocess.check_output(shlex.split("git diff --name-only " + ref_branch))
            .decode()
            .strip()
        )
        if diffs == "":
            print("\tEmpty diff, deleting branch '" + branch + "'...")
            os.system(
                "git checkout " + ref_branch + " && git branch -D '" + branch + "'"
            )
            cleaned_up += 1
        else:
            print("\tNon-empty changes. Doing nothing.")
    os.system("git checkout " + ref_branch)

    print("Cleaned up " + str(cleaned_up) + " branches.")
