#!/usr/bin/python

import os
import sys

def main(author):
    os.system(
        "git log "
        "--no-merges "
        "--author='" + author + "' "
        "--name-only "
        "--pretty=format:'' "
        "| "
        "sort -u")

if __name__ == "__main__":
    main(sys.argv[1])
