#!/usr/bin/python3

import os

import gnome
import util
import sys

def build_gtk():
    # Also needed: libgstreamer-plugins-bad1.0-dev
    os.system("meson setup " + gnome.BUILD_DIR + " .")
    os.chdir(gnome.BUILD_DIR)
    os.system("ninja")

def build_with_meson(proj, setup_flags):
    print("\n\nBuilding " + proj + "...")
    os.system(
        "meson setup " + gnome.BUILD_DIR + " --prefix=" + gnome.JHBUILD_INSTALL_DIR + " "
        "" + " ".join(setup_flags) + ""
        )
    os.system("ninja -C " + gnome.BUILD_DIR)
    os.system("ninja -C " + gnome.BUILD_DIR + " install")

def build_babl_gegl(proj):
    util.ensure_installed([
        "libjson-glib-dev",
        "libjpeg-turbo8-dev",
    ])
    setup_flags = [
        "--prefix=" + gnome.JHBUILD_INSTALL_DIR,
        "--buildtype=release",
        "-Db_lto=true"
    ]
    build_with_meson(proj, setup_flags)

def clone_or_update(url):
    os.chdir(os.path.expanduser("~") + "/repos/")
    repo_name = url.split("/")[-1].split(".git")[0]
    current_d = os.getcwd()
    if os.path.exists(repo_name):
        os.chdir(repo_name)
        os.system("git pull")
    else:
        os.system("git clone '" + url + "'")
    os.chdir(current_d)

def main():
    if not os.path.exists(gnome.JHBUILD_INSTALL_DIR):
        os.system("mkdir -p " + gnome.JHBUILD_INSTALL_DIR)
    d = os.getcwd()
    parts = d.split("/")
    proj = parts[-1]
    setup_flags = [
        "--prefix=" + gnome.JHBUILD_INSTALL_DIR
    ]

    # Tweak setup flags
    if proj == "babl" or proj == "gegl":
        setup_flags += [
            "--buildtype=release",
            "-Db_lto=true",
        ]
    elif proj == "thunar":
        util.ensure_installed([
            "libxfce4ui-2-dev",
            "xfce4-dev-tools",
            "docbook-xsl",
            "docbook-xml",
            "xsltproc",
        ])
        deps = [
          #"libxfce4util",
          "libxfce4ui",
          #"xfconf",
        ]
        for dep in deps:
            clone_or_update("https://gitlab.xfce.org/xfce/" + dep)
            os.chdir(os.path.expanduser("~") + "/repos/" + dep)
            build_with_meson(dep, setup_flags + ["-Dvala=disabled"])
            os.chdir(d)
    elif proj == "gimp":
        os.system("git submodule update --init")
        os.chdir("../babl")
        build_babl_gegl("babl")
        os.chdir(d)
        os.chdir("../gegl")
        build_babl_gegl("gegl")
        os.chdir(d)
        util.ensure_installed([
            "libappstream-glib-dev",
            "libappstream-dev",
            "libghc-gi-atk-dev",
            "libgegl-dev",
            "libgexiv2-dev",
            "libgtk-3-dev",
            "libmypaint-dev",
            "libpoppler-glib-dev",
            "librsvg2-dev",
            "libxmu-dev",
            "mypaint-brushes",
            "xsltproc",
        ])
        setup_flags += [
            "--buildtype=release",
            # "-Dpython=enabled"
        ]
    elif proj == "gnome-terminal":
        setup_flags.append("-Dsearch_provider=false")

    # Actual build

    if proj == "gtk":
        build_gtk()
    elif proj in ["babl", "gegl"]:
        build_babl_gegl(proj)
    else:
        build_with_meson(proj, setup_flags)

if __name__ == "__main__":
    main()
