#!/usr/bin/python3

import os
import util
import sys

LINE_LENGTH = 80
NEW_FILE_PATH = os.path.join(os.path.expanduser("~"), "Dropbox", "computer", "in_progress")
COMMENT_LINE = "#" * LINE_LENGTH

def separation(title):
  output = COMMENT_LINE + "\n"
  comment_prefix_length = int((LINE_LENGTH - len(title) - 2) / 2)
  output += "#" * comment_prefix_length + " " + title + " "
  output += "#" * (LINE_LENGTH - comment_prefix_length - len(title) - 2) + "\n"
  output += COMMENT_LINE + "\n"
  return output

def question_section(title, add_time=True):
  output = separation(title) + "\n"
  if add_time:
    output += "Time:\n\n\n"
  output += "\n"
  return output

output = ""

name = input("What is the candidate's name? ").strip()
resume_question = input("Resume question? ").strip()
first_question = input("First question? ").strip()
second_question = input("Second question? [Hit return for none] ").strip()

new_file = os.path.join(
    NEW_FILE_PATH,
    util.get_date_prefix() + "_" + name.replace(" ", "_").lower() + ".txt")

output += separation("Exec Summary") + "\n\n"
output += separation("Questions") + "\n"

output += "1) Resume question: " + resume_question + "\n"
output += "2) " + first_question + "\n"
if second_question != "":
  output += "3) " + second_question + "\n4) "
else:
  output += "3) "
output += "Questions for me?\n\n----\n"

output += """
* "Q:" indicates a question or comment from me
* [Comments in square brackets indicate an aside or a thought from me]
* Please use the "Code font" for more comfortable reading. Thanks!
* Entire interview conducted in English, unless specifically mentioned otherwise.
* All times in UTC.

Time at start:

"""

output += question_section("Resume Question")
output += question_section(first_question)

if second_question != "":
  output += question_section(second_question)

output += question_section("Questions for me?", add_time=False)

f = open(new_file, "w")
f.write(output)
f.close()

#print(output)
print("Wrote on: " + new_file)
