#!/usr/bin/python3

import os
import sys

percent = int(sys.argv[1])
file = sys.argv[2]

brightness = 1.0 + float(float(percent) / 10)


bup = file + ".bup"

os.system("cp " + file + " " + bup)
command = "convert -level 0%,100%," + str(brightness) + " " + file + " " + file
os.system(command)
