#!/usr/bin/python3

import os
import sys
import util

pixels = int(sys.argv[1])
f = sys.argv[2]

bup = f + ".bup"

os.system("cp " + f + " " + bup)

(w, h) = util.get_image_dimensions(f)
new_w = w - pixels

command = (
    "convert -crop "
    + str(new_w)
    + "x"
    + str(h)
    + "+0+0 +repage -gravity West "
    + f
    + " "
    + f
)
os.system(command)
