#!/usr/bin/python3

import os
import sys

file = sys.argv[2]
geom = sys.argv[1]

if not "+" in geom:
    geom = geom + "+0+0"

bup = file + ".bup"

os.system("mv " + file + " " + bup)
os.system("convert -crop " + geom + " -gravity center " + bup + " " + file)
