#!/usr/bin/python3

import os
import re
import shlex
import subprocess
import sys
import util

imgs = sys.argv[1:]

for img in imgs:
  resolution = util.get_image_resolution(img)
  spaces = " " * (20 - len(resolution))
  print(resolution + spaces + img)
