#!/usr/bin/python3

import os
import shlex
import subprocess
import sys

img = sys.argv[1]

command = "exiftool " + img

lines = subprocess.check_output(shlex.split(command)).decode().split("\n")

for l in lines:
  if "Resolution" in l:
    print(l)
