#!/usr/bin/python

import os
import sys

pic = sys.argv[1]
backup = pic + ".backup"

command = "convert -colorspace sRGB"

os.system("cp " + pic + " " + backup)
print command + " " + pic + " " + pic + "..."
os.system(command + " " + pic + " " + pic)
