#!/usr/bin/python3

import os
import sys

pic = sys.argv[1]
backup = pic + ".bup"

command = "convert -colorspace Gray"

os.system("cp " + pic + " " + backup)
#print command + " " + pic + " " + pic + "..."
os.system(command + " " + pic + " " + pic)
