#!/usr/bin/python3

import os
import sys
import util

pixels = int(sys.argv[1])
f = sys.argv[2]

bup = f + ".bup"

os.system("cp " + f + " " + bup)

(w, h) = util.get_image_dimensions(f)
new_w = w + pixels

command = (
    "convert "
    + f
    + " -background white -gravity West -splice "
    + str(pixels)
    + "x0 -extent "
    + str(new_w)
    + "x"
    + str(h)
    + " "
    + f
)
# print(command)
os.system(command)
