#!/usr/bin/python3

import os
import sys
import util

pixels = int(sys.argv[1])
f = sys.argv[2]

bup = f + ".bup"

os.system("cp " + f + " " + bup)

(w, h) = util.get_image_dimensions(f)
new_h = h + pixels

command = (
    "convert "
    + f
    + " -background white -gravity North -splice "
    + "0x"
    + str(pixels)
    + " -extent "
    + str(w)
    + "x"
    + str(new_h)
    + " "
    + f
)
# print(command)
os.system(command)
