#!/usr/bin/python

import os
import sys

def main(img):
    os.system("cp " + img + " " + img + ".bup")
    os.system("magick " + img + " -strip " + img + ".clean")
    os.system("mv " + img + ".clean " + img)

if __name__ == "__main__":
    main(sys.argv[1])
