#!/usr/bin/python3

import os
import sys
import util

png = sys.argv[1]

if not png.endswith(".png"):
  print("The given file is not PNG format")
  sys.exit(1)

bup = png + ".bup"

os.system("cp " + png + " " + bup)

command = "convert " + bup + " -background white -alpha remove " + png
os.system(command)
