#!/usr/bin/python3

import sys
import util

import PIL

DEBUG = False

def likely_year(s):
    return len(s) == 4 and (s.startswith("20") or s.startswith("19"))

def harvest_numbers_from_string(s):
    numbers = []
    current_candidate = ""
    for char in s:
        if char.isdigit():
            current_candidate += char
        else:
            if current_candidate != "":
                numbers.append(current_candidate)
            current_candidate = ""
    return numbers

if __name__ == "__main__":
    img_file = sys.argv[1]

    if DEBUG:
        util.save_image_with_modified_exif(img_file, {
          "DateTime": "Garbage",
        })

    if img_file.startswith("./"):
        img_file = img_file[2:]
    if "/" in img_file:
        filename = img_file[img_file.rindex("/") + 1:]
    else:
        filename = img_file
    try:
        exif = util.get_image_exif_data(img_file)
    except OSError as e:
        print(e)
        print("This is for file " + img_file)
    except PIL.Image.DecompressionBombError as e:
        print(e)
        print("This is for file " + img_file)
    if "DateTime" in exif:
        value = exif["DateTime"]
        if len(value) == len("YYYY:MM:DD HH:MM:SS"):
            # print("Exif date and time already there, aborting")
            sys.exit(0)

    nums = harvest_numbers_from_string(filename)
    if DEBUG:
        print(nums)
    if (len(nums) == 2 or len(nums) == 3) and len(nums[0]) == 8 and len(nums[1]) == 6:
        # Year and time in two numbers
        formatted = nums[0][0:4] + ":" + nums[0][4:6] + ":" + nums[0][6:8] + " " + \
                    nums[1][0:2] + ":" + nums[1][2:4] + ":" + nums[1][4:6]
        print("\nGuessed date and time from file name '" + filename + "': " + formatted)
        util.save_image_with_modified_exif(img_file, {
            "DateTime": formatted
        })
        sys.exit(0)
    if len(nums) in [6, 7] and likely_year(nums[0]):
        # Year and time, or maybe year and time and a duplicated "2" at the end.
        formatted = nums[0] + ":" + nums[1] + ":" + nums[2] + " " + \
                    nums[3] + ":" + nums[4] + ":" + nums[5]
        print("\nGuessed date and time from file name '" + filename + "': " + formatted)
        util.save_image_with_modified_exif(img_file, {
            "DateTime": formatted
        })
        sys.exit(0)
    if (len(nums) == 4 or len(nums) == 5) and \
        likely_year(nums[0][0:4]) and len(nums[0]) == 8 and \
        len(nums[1]) == 2 and len(nums[2]) == 2 and len(nums[3]) == 2:
        # Year and date in one number, then three numbers for time
        formatted = nums[0][0:4] + ":" + nums[0][4:6] + ":" + nums[0][6:8] + " " + \
                    nums[1] + ":" + nums[2] + ":" + nums[3]
        print("\nGuessed date and time from file name '" + filename + "': " + formatted)
        util.save_image_with_modified_exif(img_file, {
            "DateTime": formatted
        })
        sys.exit(0)

    # pieces = filename.split("_")
    # print(pieces)
    # for piece in pieces:
        # if piece.isdigit() and len(piece) == 8 and likely_year(piece):
            # formatted = piece[0:4] + ":" + piece[4:6] + ":" + piece[6:8] + " 12:00:00"
            # print("\nGuessed date " + formatted + " for " + img_file + "\n")
            # util.save_image_with_modified_exif(img_file, {
              # "DateTime": formatted
            # })
            # sys.exit(0)
        # elif piece.count("-") >= 2:
            # subpieces = piece.split("-")
            # for i in range(len(subpieces)):
                # subpiece = subpieces[i]
                # if subpiece.isdigit() and len(subpiece) == 4 and likely_year(piece) and \
                        # len(subpieces) >= i + 3 and \
                        # len(subpieces[i + 1]) == 2 and (subpieces[i + 1]).isdigit() and \
                        # len(subpieces[i + 2]) == 2 and (subpieces[i + 2]).isdigit():
                    # formatted = subpieces[i] + ":" + subpieces[i + 1] + ":" + \
                        # subpieces[i + 2] + " 12:00:00"
                    # print("\nGuessed date " + formatted + " for " + img_file + "\n")
                    # util.save_image_with_modified_exif(img_file, {
                        # "DateTime": formatted
                    # })
                    # sys.exit(0)

    # We haven't found anything yet. Let's try to use the folder name.
    print("\n\nCan only find date, no time for '" + img_file + "'\n\n")
    folders = img_file.split("/")
    for folder in folders:
        if likely_year(folder[:4]):
            y = folder[:4]
            m = folder[5:7]
            d = folder[8:10]
            formatted = y + ":" + m + ":" + d + " 12:00:00"
            if y.isdigit() and m.isdigit() and d.isdigit():
                print("\nGuessed date " + formatted + " for " + img_file + "\n")
                util.save_image_with_modified_exif(img_file, {
                    "DateTime": formatted
                })
                sys.exit(0)
