#!/usr/bin/python3

import sys
import util

import PIL

if __name__ == "__main__":
    img_file = sys.argv[1]
    try:
        exif = util.get_image_exif_data(img_file)
    except OSError as e:
        print(e)
        print("This is for file " + img_file)
    except PIL.Image.DecompressionBombError as e:
        print(e)
        print("This is for file " + img_file)
    if "DateTime" in exif:
        # print("Exif date and time already there, aborting")
        sys.exit(0)
    pieces = img_file.split("_")
    for piece in pieces:
        if piece.isdigit() and len(piece) == 8 and (piece.startswith("20") or piece.startswith("19")):
            print(piece)
            formatted = piece[0:4] + ":" + piece[4:6] + ":" + piece[6:8] + " 12:00:00"
            util.save_image_with_modified_exif(img_file, {
              "DateTime": formatted
            })
