#!/usr/bin/python3

import os

# 1. Install our official public software signing key
os.system("wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > signal-desktop-keyring.gpg")
os.system("cat signal-desktop-keyring.gpg | sudo tee -a /usr/share/keyrings/signal-desktop-keyring.gpg > /dev/null")

# 2. Add our repository to your list of repositories
os.system("echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main' |  sudo tee -a /etc/apt/sources.list.d/signal-xenial.list")

# 3. Update your package database and install signal
os.system("sudo apt update && sudo apt install signal-desktop")
