#!/usr/bin/python3

import mailbox
import os
import sys

def is_mail_dir(d):
    return "cur" in os.listdir(d)

def maildir_for_single_mail(mail_path):
    path_parts = mail_path.split(os.sep)
    current_path = os.sep.join(path_parts[:-1])
    i = 1
    while i < len(path_parts) - 1:
        current_path = os.sep.join(path_parts[:-i])
        print("Looking for mail dir at " + current_path)
        if is_mail_dir(current_path):
            print("Found")
            return mailbox.Maildir(current_path, factory=None)
        i += 1
    return None

if __name__ == "__main__":
    IN_MAIL_PATH = sys.argv[1]
    MAILDIR = maildir_for_single_mail(IN_MAIL_PATH)
