#!/usr/bin/python3

import os
import sys
import util

def main():
    i = sys.argv[1]

    args = "-background white -flatten -quality 100"

    if i.endswith(".pdf"):
        args += " -density 600"

    last_dot = i.rfind(".")
    jpg = i[:last_dot] + ".jpg"

    if i.endswith(".webp"):
        os.system("dwebp " + i + " -o " + jpg)
    elif i.lower().endswith(".nef"):
        ppm = util.change_extension(i, "ppm")
        jpg = util.change_extension(i, "jpg")
        os.system("dcraw " + i)
        os.system("mkjpg " + ppm)
        os.system("imgjpg85quality " + jpg)
        os.system("rm " + ppm)
    elif i.lower().endswith(".heic"):
        os.system("heif-convert " + i + " " + jpg)
    elif i.lower().endswith(".xcf"):
        os.system("xcf2jpg " + i)
    else:
        os.system("convert " + args + " " + i + " " + jpg)

if __name__ == "__main__":
    main()
