#!/usr/bin/python

import os
import sys
import util

origs = sys.argv[1:]

pdfs_to_delete = []
for o in origs:
  pdfs_to_delete.append(util.change_extension(o, "pdf"))
pdfs_to_delete = sorted(pdfs_to_delete)

os.system("map mkpdf " + " ".join(sys.argv[1:]))

allPdfs = " ".join(pdfs_to_delete)
print "Joining all PDFs..."
#os.system("pdfjoin " + allPdfs + " -o output.pdf")
os.system("pdftk " + allPdfs + " cat output output.pdf")
print "Deleting temporary files..."
for pdf in pdfs_to_delete:
  os.system("rm " + pdf)

print "All done!"
