#!/usr/bin/python3

import os
import sys

if len(sys.argv) < 3:
    print("Usage: " + sys.argv[0] + " size image.ext")
    print("Invocation was '" + " ".join(sys.argv) + "'")
    sys.exit(1)

s = sys.argv[1]
i = sys.argv[2]

# if "_thumbnail" in i:
    # "" + i + " is already a thumbnail, skipping"

if len(sys.argv) == 4:
    out = sys.argv[3]
else:
    extensionPos = i.rfind(".")
    out = i[:extensionPos] + "_thumbnail" + i[extensionPos:]

if os.path.exists("thumbs"):
    out = "thumbs/" + out

if os.path.exists(out) and os.path.getmtime(out) > os.path.getmtime(i):
    sys.exit(0)

command = (
    "convert -size "
    + s
    + "x"
    + s
    + " "
    + i
    + " -resize "
    + s
    + "x"
    + s
    + ' +profile "*" '
    + out
)
os.system(command)
