#!/usr/bin/python3

import os
import sys

file = sys.argv[1]

partition = file.rpartition(".")
tiff = partition[0] + ".tiff"
print "" + file + " --> " + tiff

os.system("convert " + file + " " + tiff)
