#!/usr/bin/python

import os
import sys

def main(d):
    xpi = d + ".xpi"
    os.system("rm -f " + xpi)
    os.chdir(d)
    os.system("7z a ../" + xpi + " * -r")

if __name__ == "__main__":
    main(sys.argv[1])
