#!/usr/bin/python

import os
import sys

def main(arg):
    out = arg.replace(".mp3", ".m4b")
    cmd = (
        "ffmpeg "
        "-i " + arg + " "
        # Mono
        "-ac 1 "
        # No video (will remove cover art)
        "-vn "
        "-c:a aac "
        "-b:a 32k "
        "-movflags +faststart "
        "" + out + ""
    )
    os.system(cmd)

if __name__ == "__main__":
    main(sys.argv[1])
