#!/usr/bin/python3

import os
import sys
import util

leftToRight = True

src = sys.argv[1]
(width, height) = util.get_pdf_dimension(src)

os.system("convert xc:none -page " + str(width) + "x" + str(height) + " blank.pdf")

n_pages = util.get_pdf_pages(src)
n_blank_pages_to_add = n_pages % 4
n_pages = n_pages + n_blank_pages_to_add
n_sheets = int(n_pages / 4)
print("Sheets: " + str(n_sheets))

padded_file = src.replace(".pdf", "-padded.pdf")
pad_command = "pdfjoin " + src + " " + \
    " ".join(["blank.pdf"] * n_blank_pages_to_add) + \
    " --outfile " + padded_file
os.system(pad_command)

pages = ""
for i in range(1, n_sheets + 1):
  pages += " ".join([str(p) for p in [
    2 * i - 1 + int(n_pages / 2),
    2 * i - 1,
    2 * i,
    2 * i + int(n_pages / 2),
  ]]) + " "
# Remove the last space
if pages[-1] == " ":
  pages = pages[:-1]
print(pages)
if len(pages.split(" ")) != n_pages:
  print("Houston, we have a problem, bad page count... Fix me!")
  parsed_pages = [int(p) for p in pages.split(" ")]
  for i in range(1, n_pages + 1):
    if i not in parsed_pages:
      print("Missing: " + str(i))
  sys.exit(1)

final_file = src.replace(".pdf", "-booktoslice.pdf")
command = "pdftk " + padded_file + " cat " + pages + " output " + final_file
os.system(command)

os.system("pdfnup --nup 2x1 " + final_file)
os.system("rm " + padded_file)
os.system("rm blank.pdf")
os.system("mv " + final_file.replace(".pdf", "-nup.pdf") + " " + final_file)
