#!/usr/bin/python3

import os
import sys
import util

leftToRight = True

src = sys.argv[1]
(width, height) = util.get_pdf_dimension(src)

os.system("convert xc:none -page " + str(width) + "x" + str(height) + " blank.pdf")

n_pages = util.get_pdf_pages(src)
n_pages_padded = n_pages
while n_pages_padded % 8 != 0:
  n_pages_padded += 1

n_blank_pages_to_add = n_pages_padded - n_pages
n_pages = n_pages_padded
n_sheets = int(n_pages / 8)
print("Sheets: " + str(n_sheets))

padded_file = src.replace(".pdf", "-padded.pdf")
pad_command = "java -jar ~/repos/pdftk/build/libs/pdftk-all.jar A=" + src + " B=blank.pdf cat A "
for i in range(n_blank_pages_to_add):
  pad_command = pad_command + "B "
pad_command = pad_command + "output " + padded_file
print(pad_command)
os.system(pad_command)
print("Pad command done.")

pages = ""
for i in range(1, n_sheets + 1):
  pages += " ".join([str(p) for p in [
    2 * i - 1 + 0,
    2 * i - 1 + int(n_pages / 2),
    2 * i - 1 + int(n_pages / 4),
    2 * i - 1 + int(3 * n_pages / 4),
    2 * i + 0 + int(n_pages / 2),
    2 * i + 0 + 0,
    2 * i + 0 + int(3 * n_pages / 4),
    2 * i + 0 + int(n_pages / 4),
  ]]) + " "
# Remove the last space
if pages[-1] == " ":
  pages = pages[:-1]
print(pages)
if len(pages.split(" ")) != n_pages:
  print("Houston, we have a problem, bad page count... Fix me!")
  parsed_pages = [int(p) for p in pages.split(" ")]
  for i in range(1, n_pages + 1):
    if i not in parsed_pages:
      print("Missing: " + str(i))
  sys.exit(1)

final_file = src.replace(".pdf", "-booktoslice.pdf")
command = "pdftk " + padded_file + " cat " + pages + " output " + final_file
os.system(command)

os.system("pdf90 " + final_file)
os.system("pdfjam --suffix rotated90 --angle 90 --fitpaper \
    true --rotateoversize false " + final_file)
os.system("mv " + final_file.replace(".pdf", "-rotated90.pdf") + " " + final_file)
os.system("pdfnup --nup 2x2 --rotateoversize false " + final_file)
os.system("rm " + padded_file)
os.system("rm blank.pdf")
os.system("mv " + final_file.replace(".pdf", "-nup.pdf") + " " + final_file)
