#!/usr/bin/python

import os
import sys

pdf = sys.argv[1]
prefix = pdf.replace(".pdf", "")

if not os.path.exists("extracted"):
  os.mkdir("extracted")
os.system("/usr/bin/pdfimages -j " + pdf + " extracted/" + prefix)
