#!/usr/bin/python3

import os
import sys

def main():
    pdf = sys.argv[1]
    prefix = pdf.replace(".pdf", "")

    if not os.path.exists("extracted"):
        os.mkdir("extracted")
    cmd = "/usr/bin/pdfimages -j " + pdf + " extracted/" + prefix
    print(cmd)
    os.system(cmd)

if __name__ == "__main__":
    main()
