#!/usr/bin/python3

import os
import sys

pdf = sys.argv[1]
prefix = pdf.replace(".pdf", "")

if not os.path.exists("extracted"):
    os.mkdir("extracted")
cmd = "/usr/bin/pdfimages -all " + pdf + " extracted/" + prefix
print(cmd)
os.system(cmd)
