#!/usr/bin/python3

import os
import sys
import util

pdf = sys.argv[1]
tempo = pdf.replace(".pdf", ".pdf.tempo")

pages = [1]
n_pages = util.get_pdf_pages(pdf)

pages_to_keep = [i for i in range(1, n_pages + 1)]

for p in pages:
  pages_to_keep.remove(p)

os.system("cp " + pdf + " " + pdf + ".bup")

command = "pdfjoin --rotateoversize false --fitpaper false " + pdf + " " + \
  ",".join([str(p) for p in pages_to_keep]) + " --outfile " + tempo
os.system(command)

os.system("mv " + tempo + " " + pdf)
