#!/usr/bin/python3

import os
import sys
import util

# Add some flexibility in arguments order

if ".pdf" in sys.argv[1]:
  pdf = sys.argv[1]
  pages = sys.argv[2]
elif ".pdf" in sys.argv[2]:
  pdf = sys.argv[2]
  pages = sys.argv[1]
elif "," in sys.argv[1]:
  pdf = sys.argv[2]
  pages = sys.argv[1]
elif "," in sys.argv[2]:
  pdf = sys.argv[1]
  pages = sys.argv[2]

tempo = pdf.replace(".pdf", ".pdf.tempo")

pages = [int(p) for p in pages.split(",")]
n_pages = util.get_pdf_pages(pdf)

pages_to_keep = [i for i in range(1, n_pages + 1)]

for p in pages:
  pages_to_keep.remove(p)

os.system("cp " + pdf + " " + pdf + ".bup")

command = "pdfjoin " + pdf + " " + \
  ",".join([str(p) for p in pages_to_keep]) + " --outfile " + tempo
os.system(command)

os.system("mv " + tempo + " " + pdf)

