#!/usr/bin/python3

import os
import sys

pdf = sys.argv[1]
tmppdf = pdf + ".rotated"

os.system("pdftk " + pdf + " cat 1-endwest output " + tmppdf)

os.system("gsettings set org.gnome.Evince.Default dual-page false")

os.system("evince -f " + tmppdf + " 2> /dev/null > /dev/null")

os.system("gsettings set org.gnome.Evince.Default dual-page true")

os.system("rm " + tmppdf)
