#!/usr/bin/python3

import os
import random
import sys

def radio_france_url(name, fidelity):
    return f"https://stream.radiofrance.fr/{name}/{name}_{fidelity}.m3u8?id={name}"

# fi = "lofi"
# fi = "medfi"
fi = "hifi"

streams = [
    ["bbc", "https://a.files.bbci.co.uk/ms6/live/3441A116-B12E-4D2F-ACA8-C1984642FA4B/audio/simulcast/dash/nonuk/pc_hd_abr_v2/aks/bbc_world_service.mpd"],
    ["bbc1", "http://lstn.lv/bbc.m3u8?station=bbc_radio_one&bitrate=320000"],
    ["bbcworld", "http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/ak/bbc_world_service.m3u8"],
    ["bfm", "https://audio.bfmtv.com/bfmradio_128.mp3"],
    ["bfmbusiness", "https://audio.bfmtv.com/bfmbusiness_128.mp3"],
    ["europe1", "http://ais-live.cloud-services.paris:8000/europe1.mp3"],
    ["fip", radio_france_url("fip", fi)],
    ["franceculture", radio_france_url("franceculture", fi)],
    ["franceinfo", radio_france_url("franceinfo", fi)],
    ["franceinter", radio_france_url("franceinter", fi)],
    ["francemusique", radio_france_url("francemusique", fi)],
    ["kcsm", "http://ice5.securenetsystems.net/KCSM"],
    #  ["msnbc", "http://wrau.streamguys1.com/msnbc-free"],
    ["npr", "https://fm939.wnyc.org/wnycfm-web"],
    ["rireetchansons", "http://cdn.nrjaudio.fm/audio1/fr/30401/mp3_128.mp3"],
    ["tsfjazz", "http://tsfjazz.ice.infomaniak.ch/tsfjazz-high.mp3"],
    ["wbgo", "https://wbgo.streamguys1.com/wbgo128"],
]

stream = streams[int(random.random() * len(streams))][1]
if len(sys.argv) > 1:
    if sys.argv[1] == "list":
        print("\t" + "\n\t".join([s[0] for s in streams]))
        sys.exit(0)
    for el in streams:
        if sys.argv[1].lower() in el[0]:
            print("Playing '" + el[0] + "'...")
            stream = el[1]
            break
else:
    print("I need an argument!")
    sys.exit(1)

os.system("cvlc 2> /dev/null '" + stream + "'")
