#!/usr/bin/python3

import os
import sys

from os.path import isfile, join

def main():
    for i in range(len(args)):
        f = args[i]
        extension = f[(f.rindex(".") + 1) :]
        number = str(i).zfill(5)
        new_name = number + "." + extension
        print(str(f) + " -> " + new_name + "." + extension)
        os.system("mv " + f + " " + new_name)

if __name__ == "__main__":
    args = sys.argv[1:]
    main(args)
