#!/usr/bin/python3

import math
import os
import sys

from os.path import isfile, join

def main(args):
    ten_power = int(math.log10(len(args))) + 1
    for i in range(len(args)):
        f = args[i]
        extension = f[(f.rindex(".") + 1) :]
        number = str(i).zfill(ten_power)
        new_name = number
        print(str(f) + " -> " + new_name + "." + extension)
        # os.system("mv " + f + " " + new_name)

if __name__ == "__main__":
    if len(sys.argv) == 1:
        print("Please give me the files to rename as arguments.")
    else:
        args = sys.argv[1:]
        main(args)
