#!/usr/bin/python3

import os
import re
import subprocess
import sys
import util

l = []

initial_dir = os.getcwd()

for root, dirs, files in os.walk("."):
  for d in dirs:
    full_dir = os.path.join(root, d)
    os.chdir(full_dir)
    print("Sanitizing in " + full_dir + "...")
    util.run_bin_cmd("sanitizefilenames", " ".join(["'" + f + "'" for f in os.listdir(".")]))
    os.chdir(initial_dir)

