#!/usr/bin/python3
# coding=utf-8

import os
import subprocess
import sys
import util


def rename_and_move(path):
    newName = ""
    dontModify = ""
    lastSep = path.rfind(os.path.sep)
    if lastSep != -1:
        # Copy over the dir name, unchanged
        dontModify = path[: lastSep + 1]
    lastPart = path[lastSep + 1 :]
    newName = util.sanitize_for_filename(lastPart)
    newPath = dontModify + newName
    if os.path.exists(newPath):
        print("Destination file '" + newPath + "' already exists, not overwriting")
        return
    if newPath != path:
        print(path + " -> " + newPath)
        subprocess.call(["mv", path, newPath])


filesToRename = []
dirsToRename = []

for argument in sys.argv[1:]:
    if os.path.isfile(argument):
        filesToRename.append(argument)
    elif os.path.isdir(argument):
        dirname = argument
        if dirname.endswith(os.path.sep):
            dirname = dirname[:-1]
        dirsToRename.append(dirname)

for file in filesToRename:
    rename_and_move(file)

for directory in dirsToRename:
    rename_and_move(directory)
