#!/usr/bin/python
"This is mostly just a place to hold some recipes for cmd line scanning"

import shlex
import subprocess

RESOLUTION = 600
MODE = "Gray"
SCANNER = "airscan:e0:CanonLiDE 400 (USB)"
OUTPUT = "scanned_image.png"

def main():
    print("Scanning. You may need to 'sudo apt remove ippusbxd'")
    print("If I have the wrong scanner, list them with 'scanimage -L'")
    cmd = (
        "scanimage "
        "--format png "
        "--resolution " + str(RESOLUTION) + " "
        "--mode " + MODE + " "
        "-d \"" + SCANNER + "\" "
        "-o " + OUTPUT + ""
    )
    subprocess.check_output(shlex.split(cmd))

if __name__ == "__main__":
    main()
