#!/usr/bin/python3

import os
import re
import shlex
import subprocess
import sys

raw = subprocess.check_output(shlex.split("xrandr --listactivemonitors")).decode()

dpis = []
for i in range(10):
  for l in raw.split("\n"):
    l = l.strip()
    parts = l.split(" ")
    if parts[0] == str(i) + ":":
      matches = re.match(r"(\d+)/(\d+)x(\d+)/(\d+)", parts[2])
      (w_px, w_mm, h_px, h_mm) = \
          (int(matches.group(1)), int(matches.group(2)),
           int(matches.group(3)), int(matches.group(4)))
      w_in = float(w_mm) / 25.4
      h_in = float(h_mm) / 25.4
      dpi_x = int(float(w_px) / w_in)
      dpi_y = int(float(h_px) / h_in)
      dpi = int(float((dpi_x + dpi_y) / 2))
      dpis.append(dpi)

print(str(dpis))
