#!/usr/bin/python3

import os

os.system(
    "wget -qO - https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -"
)
os.system(
    "sudo sh -c 'echo \"deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main\" > /etc/apt/sources.list.d/atom.list'"
)
os.system("sudo apt-get update")
os.system("sudo apt-get -y install atom")
