#!/usr/bin/python3

# Stolen and adapted from
# https://codereview.stackexchange.com/questions/8958/n-largest-files-in-a-directory

import heapq
import os, os.path
import sys
import operator


def file_sizes(directory):
    for path, _, filenames in os.walk(directory):
        for name in filenames:
            full_path = os.path.join(path, name)
            if not os.path.exists(full_path):
                continue
            yield full_path, os.path.getsize(full_path)


num_files = int(sys.argv[1]) if len(sys.argv) > 1 else 20
directory = sys.argv[2] if len(sys.argv) > 2 else os.getcwd()


big_files = heapq.nlargest(num_files, file_sizes(directory), key=operator.itemgetter(1))

for f in big_files:
    size_gb = str(round(f[1] / 1024.0 / 1024.0 / 1024.0, 2)) + " GB"
    print(size_gb + "\t" + f[0])
