#!/usr/bin/python3

import os

dry_run = False
# Careful! Don't set this to True because of chromium
delete = False

suzerain = os.path.join(os.path.expanduser("~"), "Dropbox")
vassals = [
  os.path.join(os.path.expanduser("~"), "pCloudDrive"),
]

for v in vassals:
  cmd = ("rsync "
         "-av " + ("-n " if dry_run else "") + ""
         "" + suzerain + "/ "
         "" + v + "/")
  if delete:
    cmd += " --delete"
  print(cmd)
  os.system(cmd)
