#!/usr/bin/python3

import os
import shlex
import subprocess
import sys

dry_run = False
delete = True

suzerain = os.path.join(os.path.expanduser("~"), "Dropbox")
vassals = [
    os.path.join(os.path.expanduser("~"), "pCloudDrive"),
]

for v in vassals:
    cmd = ("rsync "
           "-av " + ("-n " if dry_run else "") + ""
           "" + suzerain + "/ "
           "" + v + "/")
    if delete:
        cmd += " --delete"
    print(cmd)
    process = subprocess.Popen(shlex.split(cmd), stdout=subprocess.PIPE)
    # Only show files, not directories
    for line in iter(process.stdout.readline, b''):
        l = line.decode().strip()
        if l.endswith("/"):
            sys.stdout.write(".")
            sys.stdout.flush()
        else:
            print(l)
