#!/usr/bin/python3

import shlex
import subprocess

import util

COLORS = [
    ["red",    [1, 2, 3]],
    ["yellow", [4, 5, 6]],
    ["green",  [7, 8, 9]],
    ["cyan",   [0]],
]

def format(raw):
    for l in raw.split("\n"):
        l = l.strip()
        if len(l) < 2 or l[1] != ".":
            continue
        pri = int(l[0])
        for _, c in enumerate(COLORS):
            if pri in c[1]:
                print(util.color(l, c[0]))

if __name__ == "__main__":
    RAW = subprocess.check_output(shlex.split("calcurse --todo")).decode()
    format(RAW)
