#!/usr/bin/python

import json
import os
import shlex
import subprocess
import sys

home = os.path.expanduser("~")

def adjust_vscode(up):
    os.chdir(home)
    settings = "bus/config/config/Code/User/settings.json"
    o = None
    with open(settings) as f:
        try:
            o = json.load(f)
        except json.decoder.JSONDecodeError as e:
            print("Oops: " + str(e))
            return

    if "window.zoomLevel" in o:
        current_zoom = o["window.zoomLevel"]
        new_zoom = current_zoom + (0.5 if up else -0.5)
        new_zoom = max(0.2, new_zoom)
        new_zoom = min(10, new_zoom)
        o["window.zoomLevel"] = new_zoom

    with open(settings, "w") as f:
        f.write(json.dumps(o, indent=2))

def adjust_gedit(up):
    pref_name = "org.gnome.gedit.preferences.editor editor-font"
    current = subprocess.check_output(shlex.split(
        "gsettings get " + pref_name
    )).decode().strip()

    if current.startswith("'"):
        current = current[1:]
    if current.endswith("'"):
        current = current[:-1]
    font = " ".join(current.split(" ")[:-1])
    current_size = int(current.split(" ")[-1])
    new_size = current_size + (2 if up else -2)
    new_size = max(6, new_size)
    new_size = min(50, new_size)
    os.system("gsettings set " + pref_name + " \"" + font + " " + str(new_size) + "\"")

def main(up):
    # print("Adjusting text size " + ("up" if up else "down"))
    adjust_vscode(up)
    adjust_gedit(up)

if __name__ == "__main__":
    up = sys.argv[1] in ["u", "+"]
    main(up)
