#!/usr/bin/python3

import datetime
import sys

from pytz import timezone

import timezones

TZ_TO_INCLUDE = ["PST", "MST", "CST", "EST", "UTC", "CET", "CNT", "JST"]

def convert(d, tz_from, tz_to):
    to_tz = timezone(timezones.TIMEZONES[tz_to])
    ts = d.timestamp()
    return datetime.datetime.fromtimestamp(ts).astimezone(to_tz)

def format_time(d):
    return d.strftime("%H:%M")

if __name__ == "__main__":
    t = sys.argv[1]

    if len(sys.argv) < 3:
        z = "UTC"
    else:
        z = sys.argv[2]

    if ":" in t:
        (h, m) = [int(e) for e in t.split(":")]
    else:
        h = int(t)
        m = 0

    d = datetime.datetime.now()
    d = d.replace(hour=h, minute=m, second=0)
    d = timezone(timezones.TIMEZONES[z]).localize(d)

    if len(z) == 1:
        z = timezones.SHORTS[z]

    print(format_time(d) + " " + z + "\n"
          " \n"
          "    | \n"
          "    v "
          " \n")
    for tz in TZ_TO_INCLUDE:
        print(format_time(convert(d, z, tz)) + " " + tz)
