#!/usr/bin/perl

$garder = shift @ARGV or die "Usage: $0 nb_de_caract_a_garder_a_la_fin fichiers\n";

for (@ARGV) 
	{
	$tempo = substr($_, length($_) - $garder - 1, $garder + 1);
	$do .= "mv $_ $tempo;"
	}

system ($do);
#print "$do\n";
