#!/usr/bin/python

import os
import sys

def main(args):
    # 7z seems better at extracting zip files than built-in unzip
    os.system("7z x " + " ".join(args))

if __name__ == "__main__":
    main(sys.argv[1:])
