#!/usr/bin/python3

import os
import re
import shlex
import subprocess
import sys

TRACK_ID_REGEXP = r"Track\s+ID\s+(.+)\:\s+.*"

def remove_track_by_id(i, new_file, bup_file):
    print("Removing track " + i)
    cmd = "mkvmerge -o " + new_file + " --audio-tracks !" + i + " " + bup_file
    os.system(cmd)

def remove_track_by_number(n, info, new_file, bup_file):
    audio_track_numbers = []
    for l in info.split("\n"):
        if l.startswith("Track ID") and "audio" in l:
            audio_track_numbers.append(int(re.match(TRACK_ID_REGEXP, l).group(1)))

    print("Audio tracks: " + str(audio_track_numbers))

    if n in audio_track_numbers:
        print("Removing track #" + str(n))
        cmd = "mkvmerge -o " + new_file + " --audio-tracks !" + str(n) + " " + bup_file
        os.system(cmd)

def main():
    input_file = sys.argv[2]
    info = subprocess.check_output(shlex.split("mkvmerge -i " + input_file)).decode()
    if len(sys.argv) < 3:
        print("Give me a track to remove. Here is the list: " + str(info))
        sys.exit(1)

    bup = input_file + ".bup"
    os.system("mv " + input_file + " " + bup)

    if sys.argv[1].isdigit():
        track_number = int(sys.argv[1])
        remove_track_by_number(track_number, info, input_file, bup)
    else:
        track_id = sys.argv[1]
        remove_track_by_id(track_id, input_file, bup)

if __name__ == "__main__":
    main()





