#!/usr/bin/python3

import os
import sys
import util

TRACK_ID_REGEXP = r"Track\s+ID\s+(.+)\:\s+.*"

input = sys.argv[1]
bup = input + ".bup"
os.system("mv " + input + " " +  bup)
input = util.change_extension(input, "mp4")

#subtitles_option = "-vf subtitles=" + input + " " if input.endswith(".mkv") else ""
subtitles_option = ""
cmd = ("ffmpeg -i " + bup + " "
       "" + subtitles_option + ""
       "-c:v libx264 "
       "-c:a aac "
       "-filter:a \"loudnorm, aformat=channel_layouts=stereo\" " + input)
print(cmd)
os.system(cmd)
