#!/usr/bin/python3

import os
import sys

if __name__ == "__main__":
    movie = sys.argv[1]
    subs = sys.argv[2]
    dot_index = movie.rfind(".")
    out = movie[:dot_index] + "_burned" + movie[dot_index:]

    cmd = ("ffmpeg "
           "-i " + movie + " "
           "-vf subtitles=" + subs + " "
           "" + out)

    # print(cmd)
    os.system(cmd)
