#!/usr/bin/python3

import os
import re
import shlex
import subprocess
import sys
import util

v = sys.argv[1]
output = util.change_extension(v, "mp3")

os.system("ffmpeg -i " + v + " " + output)
# os.system("ffmpeg -i " + input + " -q:a 0 -map a " + output)
