#!/usr/bin/python3

import os
import re
import shlex
import subprocess
import sys

TRACK_ID_REGEXP = r"Track\s+ID\s+(.+)\:\s+.*"

def main():
    input = sys.argv[1]
    tracks = [int(arg) for arg in sys.argv[2:]]
    bup = input + ".bup"

    info = subprocess.check_output(shlex.split("mkvmerge -i " + input)).decode()

    subtitle_track_numbers = []
    for l in info.split("\n"):
        if l.startswith("Track ID") and "subtitles" in l:
            subtitle_track_numbers.append(int(re.match(TRACK_ID_REGEXP, l).group(1)))

    print("Subtitle tracks: " + str(subtitle_track_numbers))

    for track in tracks:
        if track not in subtitle_track_numbers:
            print("Sorry, track " + str(track) + " is not in subtitles")

    print("Removing tracks " + str(tracks))
    os.system("mv " + input + " " + bup)
    option = "!" + ",".join([str(t) for t in tracks])
    os.system("mkvmerge -o " + input + " --subtitle-tracks " + option + " " + bup)

if __name__ == "__main__":
    main()
