#!/usr/bin/python3

import os
import sys
import util

directory = sys.argv[1]

os.chdir(directory)
videos = os.listdir(".")

# Assume they all have the same extension
ext = util.get_extension(videos[0])

videos = [v for v in videos if v.endswith(ext)]

util.run_bin_cmd("videoconcat", args=" ".join(videos))
os.system("mv output." + ext + " ../" + directory + "." + ext)
