#!/usr/bin/python

import os
import sys

def main(v, pixels):
    bup = v + '.bup'
    os.system("mv '" + v + "' '" + bup + "'")
    os.system(
        "ffmpeg -i '" + bup + "' "
        "-vf \"crop=iw-" + str(pixels) + ":ih:0:0\" "
        "-c:a copy " + v
    )

if __name__ == "__main__":
    v = sys.argv[1]
    pixels = sys.argv[2]
    main(v, pixels)
