#!/usr/bin/python3

import os
import sys

in_video = sys.argv[1]
period = int(sys.argv[2])

fps = 1 / period

cmd = "ffmpeg -i " + in_video + " -vf fps=" + str(fps) + " capture_%d.png"
print(cmd)
os.system(cmd)
