#!/usr/bin/python3

import os
import re
import shlex
import subprocess
import sys

TRACK_ID_REGEXP = r"Track\s+ID\s+(.+)\:\s+.*"

track = int(sys.argv[1])
input = sys.argv[2]
bup = input + ".bup"

info = subprocess.check_output(shlex.split("mkvmerge -i " + input)).decode()

audio_track_numbers = []
for l in info.split("\n"):
  if l.startswith("Track ID") and "audio" in l:
    audio_track_numbers.append(int(re.match(TRACK_ID_REGEXP, l).group(1)))

print("Audio tracks: " + str(audio_track_numbers))

if track in audio_track_numbers:
  print("Removing track " + str(track))
  os.system("mv " + input + " " + bup)
  cmd = "mkvmerge -o " + input + " --audio-tracks !" + str(track) + " " + bup
  os.system(cmd)
