#!/usr/bin/python

import os
import sys

def main(arg):
    bup = arg + ".bup"
    os.system("mv " + arg + " " + bup)
    cmd = (
        "ffmpeg "
        "-i " + bup + " "
        "-c:v libx265 "
        # Quality
        "-crf 28 "
        "-c:a aac "
        "-b:a 128k "
        "" + arg + ""
    )
    os.system(cmd)

if __name__ == "__main__":
    main(sys.argv[1])
