#!/usr/bin/python

import os

def main():
    # Sigh
    # Removing for now, relying on apparmor having been uninstalled
    # os.system("sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0")
    os.system("/usr/bin/code")

if __name__ == "__main__":
    main()
