#!/usr/bin/python3

"""
A little weird that 'watch' doesn't have an option not to highlight differences
"""

import os
import sys

cmd = sys.argv[1]
delay = int(sys.argv[2])

os.system(
    "clear && "
    "" + cmd + "; "
    "while sleep " + str(delay) + "; "
    "do clear; " + cmd + "; "
    "done"
)
