#!/usr/bin/python3

import shlex
import subprocess
import util

if util.is_online():
    try:
        my_ip = subprocess.check_output(shlex.split("curl -s ipinfo.io/ip")).decode()
        location_info = subprocess.check_output(
            shlex.split("curl -s ipinfo.io/" + my_ip)
        ).decode()
        print(location_info)
    except subprocess.CalledProcessError:
        print("You are offline")
else:
    print("You are offline")
