#!/usr/bin/python

import os
import sys

import windowmanager

from virtualdesktops import ARABIC, ROMAN, CHINESE

N_ROWS = 3
N_COLS = 3

ARABIC_NUMERALS = ARABIC.split(" ")
ROMAN_NUMERALS = ROMAN.split(" ")
CHINESE_NUMERALS = CHINESE.split(" ")

ALL_NUMERALS = [
    ARABIC_NUMERALS, ROMAN_NUMERALS, CHINESE_NUMERALS,
]

def switch(current, direction):
    # Always synchronize monitors, but remember which one was active originally
    principal = 0
    square = N_COLS * N_ROWS
    while current > square:
        current -= square
        principal += 1
    target = windowmanager.select_target_workspace(N_ROWS, N_COLS, current, direction)
    while target > square:
        target -= square

    if target != current:
        workspace_to_refocus_at_the_end = target + principal * square
        focused_monitor = windowmanager.get_focused_monitor()
        monitor_ids = windowmanager.get_monitor_ids()
        i = 0
        for monitor_id in monitor_ids:
            if windowmanager.is_bspwm():
                target_ws_id = ALL_NUMERALS[i % 3][target - 1]
            elif windowmanager.is_hyprland():
                target_ws_id = str(target + N_COLS * N_ROWS * i)
            else:
                target_ws_id = str(target)
            windowmanager.focus_monitor_with_id(monitor_id)
            windowmanager.focus_workspace_with_name(target_ws_id)
            #windowmanager.notify("Switching to workspace " + str(target_ws_id))
            i += 1
        windowmanager.focus_workspace_with_name(workspace_to_refocus_at_the_end)

        # Restore focused monitor
        windowmanager.focus_monitor_with_id(focused_monitor)
        icon_filename = (
            "workspace_"
            "" + str(N_ROWS) + "x"
            "" + str(N_COLS) + "_"
            "" + str(target) + ""
            ".svg"
        )
        icon_path = os.path.join(os.path.expanduser("~"), "bus", "reference", "workspace_icons",
            icon_filename)
        windowmanager.notify(" ", icon_path)

if __name__ == "__main__":
    DIRECTION = sys.argv[1]
    CURRENT = windowmanager.get_focused_workspace_name()
    if CURRENT in ROMAN_NUMERALS:
        CURRENT = ROMAN_NUMERALS.index(CURRENT) + 1
    if CURRENT in CHINESE_NUMERALS:
        CURRENT = CHINESE_NUMERALS.index(CURRENT) + 1
    switch(int(CURRENT), DIRECTION)
