#!/usr/bin/python

import sys

import gimp

SCHEME_SCRIPT = """
(define (xcf-to-png filename)
  (let* ((image (car (gimp-file-load RUN-NONINTERACTIVE filename filename))))
    (gimp-message (string-append "Loaded image " filename))
    (let* ((flattened (gimp-image-flatten image))
          )
      (
        let ((png_filename (string-append (substring filename 0 (- (string-length filename) 4)) ".png")))
        (gimp-message png_filename)

        (
          let ((layer (car (gimp-image-merge-visible-layers image CLIP-TO-IMAGE))))
          (gimp-file-save RUN-NONINTERACTIVE image png_filename png_filename)
        )
      )
    )
    (gimp-image-delete image)
  )
)

"""

def main(xcf):
    gimp.run_script(SCHEME_SCRIPT, "(xcf-to-png \"" + xcf + "\")"
)

if __name__ == "__main__":
    main(sys.argv[1])
