#!/usr/bin/python

import os
import sys

def main(xcf):
    jpg = xcf.replace(".xcf", ".jpg")
    os.system(
      "convert "
      "-flatten "
      "-background white "
      "" + xcf + " "
      " " + jpg + ""
    )

if __name__ == "__main__":
    main(sys.argv[1])
