#!/usr/bin/python

import os
import sys

def main(xcf):
    png = xcf.replace(".xcf", ".png")
    os.system(
      "convert "
      "-alpha on "
      "-background none "
      "-layers merge "
      "" + xcf + " "
      " " + png + ""
    )

if __name__ == "__main__":
    main(sys.argv[1])
