#!/usr/bin/python3

import os

# Add the deb source
os.system("sudo sh -c 'echo \"deb https://hub.unity3d.com/linux/repos/deb stable main\" > /etc/apt/sources.list.d/unityhub.list'")

# Add the public signing key
os.system("wget -qO - https://hub.unity3d.com/linux/keys/public | sudo apt-key add -")

# Update and install
os.system("sudo apt update && sudo apt install unityhub")
