#!/usr/bin/python

import os

def main():
    if not os.path.exists("/usr/bin/steam"):
        os.system("wget https://cdn.akamai.steamstatic.com/client/installer/steam.deb")
        os.system("sudo dpkg -i steam.deb")
    os.system("sudo dpkg --add-architecture i386")
    os.system("sudo apt update")
    os.system("sudo apt install libgl1:i386 libdrm2:i386 libc6:amd64 libc6:i386 libegl1:amd64 libegl1:i386 libgbm1:amd64 libgbm1:i386 libgl1-mesa-dri:amd64 libgl1-mesa-dri:i386 libgl1:amd64 libgl1:i386 steam-libs-amd64:amd64 steam-libs-i386:i386")

if __name__ == "__main__":
    main()
