#!/usr/bin/python

import os

HOME = os.path.expanduser("~")

DEPS = [
  "wayland-protocols",
  "libwlroots-0.18",
  "libxkbcommon-dev",
  "zig",
]

def main():
    os.system("sudo apt install " + " ".join(DEPS))
    os.chdir(HOME)
    if not os.path.exists('river'):
        os.system("git clone 'git@github.com:riverwm/river.git'")
    os.chdir("river")
    os.system("git pull")
    os.system("/usr/local/bin/zig/zig build -Doptimize=ReleaseSafe --prefix ~/.local install")

if __name__ == "__main__":
    main()
